/**
 * Car Fleet Data
 * Central repository for all vehicle information.
 * Images sourced from Unsplash CDN — high-quality, royalty-free.
 */

export const CARS = [
    {
        id: 1,
        brand: "Toyota",
        name: "Corolla 2024",
        cat: "economy",
        image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80",
        engine: "1.8L 4-cyl",
        seats: 5,
        trans: "Auto",
        price: 45,
        avail: true,
        rating: 4.6,
        fuel: "Petrol",
        features: ["Bluetooth", "Backup Camera", "Lane Assist"],
    },
    {
        id: 2,
        brand: "Honda",
        name: "Civic RS 2024",
        cat: "sedan",
        image: "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80",
        engine: "2.0L VTEC",
        seats: 5,
        trans: "Manual",
        price: 55,
        avail: true,
        rating: 4.7,
        fuel: "Petrol",
        features: ["Sport Mode", "Apple CarPlay", "LED Lights"],
    },
    {
        id: 3,
        brand: "Kia",
        name: "Sportage X 2024",
        cat: "suv",
        image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80",
        engine: "2.5L AWD",
        seats: 7,
        trans: "Auto",
        price: 85,
        avail: true,
        rating: 4.7,
        fuel: "Petrol",
        features: ["AWD", "Panoramic Roof", "7 Seats"],
    },
    {
        id: 4,
        brand: "BMW",
        name: "X5 M Sport 2024",
        cat: "luxury",
        image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
        engine: "3.0L TwinTurbo",
        seats: 5,
        trans: "Auto",
        price: 180,
        avail: false,
        rating: 4.8,
        fuel: "Petrol",
        features: ["M Performance", "Harman Kardon", "Night Vision"],
    },
    {
        id: 5,
        brand: "Suzuki",
        name: "Alto 660cc",
        cat: "economy",
        image: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80",
        engine: "660cc 3-cyl",
        seats: 4,
        trans: "Auto",
        price: 28,
        avail: true,
        rating: 4.3,
        fuel: "Petrol",
        features: ["Fuel Efficient", "Compact", "Easy Parking"],
    },
    {
        id: 6,
        brand: "Mercedes-Benz",
        name: "E-Class 2024",
        cat: "luxury",
        image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80",
        engine: "2.0L Turbo",
        seats: 5,
        trans: "Auto",
        price: 220,
        avail: true,
        rating: 4.9,
        fuel: "Hybrid",
        features: ["Burmester Audio", "Massage Seats", "MBUX"],
    },
    {
        id: 7,
        brand: "Hyundai",
        name: "Tucson N Line",
        cat: "suv",
        image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80",
        engine: "1.6L Turbo",
        seats: 5,
        trans: "DCT",
        price: 78,
        avail: true,
        rating: 4.6,
        fuel: "Petrol",
        features: ["N Line Sport", "BlueLink", "Wireless Charging"],
    },
    {
        id: 8,
        brand: "Audi",
        name: "A4 2024",
        cat: "sedan",
        image: "https://images.unsplash.com/photo-1614026480418-bd11fdb9fa06?w=800&q=80",
        engine: "2.0L TFSI",
        seats: 5,
        trans: "S-Tronic",
        price: 130,
        avail: true,
        rating: 4.8,
        fuel: "Petrol",
        features: ["Virtual Cockpit", "Matrix LED", "Bang & Olufsen"],
    },
    {
        id: 9,
        brand: "Ferrari",
        name: "Roma 2024",
        cat: "luxury",
        image: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=800&q=80",
        engine: "3.9L V8",
        seats: 2,
        trans: "8-DCT",
        price: 650,
        avail: true,
        rating: 5.0,
        fuel: "Petrol",
        features: ["620 HP", "0-100 in 3.4s", "Maranello Crafted"],
    },
];

export const PRICING_RATES = {
    economy: 28,
    sedan:   55,
    suv:     85,
    luxury:  180,
};

export const CAR_CATEGORIES = ["all", "economy", "sedan", "suv", "luxury"];

export const NAV_LINKS = ["Home", "Fleet", "Booking", "Admin", "Database", "About"];

// Legacy static bookings — now superseded by BookingContext but kept for backward compat
export const BOOKINGS_DATA = [];
